### ISSUE TITLE
Can not start examples with `ros2 launch turtlebot4_python_examples followbot.launch.py`

### ISSUE THREAD

**Issue by Kohl-Stefan** [turtlebot/turtlebot4_examples#2]
- OS: Ubuntu 20.04
 - ROS Distro: Galactic

I want to try out the turtlebot4_examples like the followbot example, but when I launch the example an Package not found error occurs. Do you have an idea where the problem might be?

Provide the steps to reproduce:
1. clone the turtlebot4_example folder to the source of the workspace on turtlebot4
2. colcon build the package 
3. source the setup.bash of overlay
4. `ros2 launch turtlebot4_python_examples followbot.launch.py`

Error occurs:

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-04-21-14-53-16-061947-ubuntu-1874
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [turtlebot4_node-1]: process started with pid [1877]
[INFO] [joy_linux_node-2]: process started with pid [1879]
[INFO] [teleop_node-3]: process started with pid [1881]
[INFO] [mobilenet_spatial_node-4]: process started with pid [1883]
[INFO] [robot_state_publisher-5]: process started with pid [1886]
[INFO] [followbot-6]: process started with pid [1895]
[turtlebot4_node-1] [INFO] [1650552800.049266194] [turtlebot4_node]: Init Turtlebot4 Node Main
[joy_linux_node-2] [ERROR] [1650552800.099527129] [joy_linux_node]: Couldn't open joystick /dev/input/js0. Will retry every second.
[teleop_node-3] [INFO] [1650552800.191458880] [TeleopTwistJoy]: Teleop enable button 4.
[teleop_node-3] [INFO] [1650552800.204610029] [TeleopTwistJoy]: Turbo on button 5.
[teleop_node-3] [INFO] [1650552800.207889664] [TeleopTwistJoy]: Linear axis x on 1 at scale 0.200000.
[teleop_node-3] [INFO] [1650552800.214736893] [TeleopTwistJoy]: Turbo for linear axis x is scale 0.500000.
[teleop_node-3] [INFO] [1650552800.214791096] [TeleopTwistJoy]: Angular axis yaw on 0 at scale 0.500000.
[teleop_node-3] [INFO] [1650552800.214814596] [TeleopTwistJoy]: Turbo for angular axis yaw is scale 1.900000.
[robot_state_publisher-5] The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-5] Link bump_front_center had 0 children
[robot_state_publisher-5] Link bump_front_left had 0 children
[robot_state_publisher-5] Link bump_front_right had 0 children
[robot_state_publisher-5] Link bump_left had 0 children
[robot_state_publisher-5] Link bump_right had 0 children
[robot_state_publisher-5] Link button_1 had 0 children
[robot_state_publisher-5] Link button_2 had 0 children
[robot_state_publisher-5] Link button_power had 0 children
[robot_state_publisher-5] Link cliff_front_left had 0 children
[robot_state_publisher-5] Link cliff_front_right had 0 children
[robot_state_publisher-5] Link cliff_side_left had 0 children
[robot_state_publisher-5] Link cliff_side_right had 0 children
[robot_state_publisher-5] Link front_caster_link had 0 children
[robot_state_publisher-5] Link imu_link had 0 children
[robot_state_publisher-5] Link ir_intensity_front_center_left had 0 children
[robot_state_publisher-5] Link ir_intensity_front_center_right had 0 children
[robot_state_publisher-5] Link ir_intensity_front_left had 0 children
[robot_state_publisher-5] Link ir_intensity_front_right had 0 children
[robot_state_publisher-5] Link ir_intensity_left had 0 children
[robot_state_publisher-5] Link ir_intensity_right had 0 children
[robot_state_publisher-5] Link ir_intensity_side_left had 0 children
[robot_state_publisher-5] Link ir_omni had 0 children
[robot_state_publisher-5] Link mouse had 0 children
[robot_state_publisher-5] Link oakd_lite_camera_bracket had 1 children
[robot_state_publisher-5] Link oakd_lite_link had 4 children
[robot_state_publisher-5] Link oakd_lite_imu_frame had 0 children
[robot_state_publisher-5] Link oakd_lite_left_camera_frame had 1 children
[robot_state_publisher-5] Link oakd_lite_left_camera_optical_frame had 0 children
[robot_state_publisher-5] Link oakd_lite_rgb_camera_frame had 1 children
[robot_state_publisher-5] Link oakd_lite_rgb_camera_optical_frame had 0 children
[robot_state_publisher-5] Link oakd_lite_right_camera_frame had 1 children
[robot_state_publisher-5] Link oakd_lite_right_camera_optical_frame had 0 children
[robot_state_publisher-5] Link rplidar_link had 0 children
[robot_state_publisher-5] Link wheel_drop_left had 1 children
[robot_state_publisher-5] Link left_wheel had 0 children
[robot_state_publisher-5] Link wheel_drop_right had 1 children
[robot_state_publisher-5] Link right_wheel had 0 children
[robot_state_publisher-5] [INFO] [1650552800.344088630] [robot_state_publisher]: got segment base_link
[robot_state_publisher-5] [INFO] [1650552800.344732383] [robot_state_publisher]: got segment bump_front_center
[robot_state_publisher-5] [INFO] [1650552800.344864178] [robot_state_publisher]: got segment bump_front_left
[robot_state_publisher-5] [INFO] [1650552800.344917603] [robot_state_publisher]: got segment bump_front_right
[robot_state_publisher-5] [INFO] [1650552800.344959436] [robot_state_publisher]: got segment bump_left
[robot_state_publisher-5] [INFO] [1650552800.344999195] [robot_state_publisher]: got segment bump_right
[robot_state_publisher-5] [INFO] [1650552800.354040107] [robot_state_publisher]: got segment button_1
[robot_state_publisher-5] [INFO] [1650552800.354245197] [robot_state_publisher]: got segment button_2
[robot_state_publisher-5] [INFO] [1650552800.354327400] [robot_state_publisher]: got segment button_power
[robot_state_publisher-5] [INFO] [1650552800.354379326] [robot_state_publisher]: got segment cliff_front_left
[robot_state_publisher-5] [INFO] [1650552800.354424918] [robot_state_publisher]: got segment cliff_front_right
[robot_state_publisher-5] [INFO] [1650552800.354468584] [robot_state_publisher]: got segment cliff_side_left
[robot_state_publisher-5] [INFO] [1650552800.354562546] [robot_state_publisher]: got segment cliff_side_right
[robot_state_publisher-5] [INFO] [1650552800.354618731] [robot_state_publisher]: got segment front_caster_link
[robot_state_publisher-5] [INFO] [1650552800.354659730] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-5] [INFO] [1650552800.354700563] [robot_state_publisher]: got segment ir_intensity_front_center_left
[robot_state_publisher-5] [INFO] [1650552800.354770137] [robot_state_publisher]: got segment ir_intensity_front_center_right
[robot_state_publisher-5] [INFO] [1650552800.354815081] [robot_state_publisher]: got segment ir_intensity_front_left
[robot_state_publisher-5] [INFO] [1650552800.354857191] [robot_state_publisher]: got segment ir_intensity_front_right
[robot_state_publisher-5] [INFO] [1650552800.354900006] [robot_state_publisher]: got segment ir_intensity_left
[robot_state_publisher-5] [INFO] [1650552800.354949672] [robot_state_publisher]: got segment ir_intensity_right
[robot_state_publisher-5] [INFO] [1650552800.354989949] [robot_state_publisher]: got segment ir_intensity_side_left
[robot_state_publisher-5] [INFO] [1650552800.355036708] [robot_state_publisher]: got segment ir_omni
[robot_state_publisher-5] [INFO] [1650552800.355074282] [robot_state_publisher]: got segment left_wheel
[robot_state_publisher-5] [INFO] [1650552800.355115133] [robot_state_publisher]: got segment mouse
[robot_state_publisher-5] [INFO] [1650552800.355162225] [robot_state_publisher]: got segment oakd_lite_camera_bracket
[robot_state_publisher-5] [INFO] [1650552800.355205651] [robot_state_publisher]: got segment oakd_lite_imu_frame
[robot_state_publisher-5] [INFO] [1650552800.355247687] [robot_state_publisher]: got segment oakd_lite_left_camera_frame
[robot_state_publisher-5] [INFO] [1650552800.355287280] [robot_state_publisher]: got segment oakd_lite_left_camera_optical_frame
[robot_state_publisher-5] [INFO] [1650552800.355331001] [robot_state_publisher]: got segment oakd_lite_link
[robot_state_publisher-5] [INFO] [1650552800.355371797] [robot_state_publisher]: got segment oakd_lite_rgb_camera_frame
[robot_state_publisher-5] [INFO] [1650552800.355415334] [robot_state_publisher]: got segment oakd_lite_rgb_camera_optical_frame
[robot_state_publisher-5] [INFO] [1650552800.355453945] [robot_state_publisher]: got segment oakd_lite_right_camera_frame
[robot_state_publisher-5] [INFO] [1650552800.355556758] [robot_state_publisher]: got segment oakd_lite_right_camera_optical_frame
[robot_state_publisher-5] [INFO] [1650552800.355628702] [robot_state_publisher]: got segment right_wheel
[robot_state_publisher-5] [INFO] [1650552800.355668128] [robot_state_publisher]: got segment rplidar_link
[robot_state_publisher-5] [INFO] [1650552800.355706183] [robot_state_publisher]: got segment wheel_drop_left
[robot_state_publisher-5] [INFO] [1650552800.355742923] [robot_state_publisher]: got segment wheel_drop_right
[turtlebot4_node-1] [INFO] [1650552800.543559237] [turtlebot4_node]: Buttons Init
[turtlebot4_node-1] [INFO] [1650552800.560776939] [turtlebot4_node]: Turtlebot4 lite running.
[followbot-6] Traceback (most recent call last):
[followbot-6]   File "/home/ubuntu/dev_ws/install/turtlebot4_python_examples/lib/turtlebot4_python_examples/followbot", line 11, in <module>
[followbot-6]     load_entry_point('turtlebot4-python-examples==0.1.0', 'console_scripts', 'followbot')()
[followbot-6]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
[followbot-6]     return get_distribution(dist).load_entry_point(group, name)
[followbot-6]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
[followbot-6]     return ep.load()
[followbot-6]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
[followbot-6]     return self.resolve()
[followbot-6]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
[followbot-6]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[followbot-6] ModuleNotFoundError: No module named 'turtlebot4_python_examples.FollowBot'
[ERROR] [followbot-6]: process has died [pid 1895, exit code 1, cmd '/home/ubuntu/dev_ws/install/turtlebot4_python_examples/lib/turtlebot4_python_examples/followbot --ros-args'].
[mobilenet_spatial_node-4] [2022-04-21 14:53:27.557] [warning] Insufficient permissions to communicate with X_LINK_BOOTED device having name "2.2". Make sure udev rules are set
[mobilenet_spatial_node-4] terminate called after throwing an instance of 'std::runtime_error'
[mobilenet_spatial_node-4]   what():  No available devices
[ERROR] [mobilenet_spatial_node-4]: process has died [pid 1883, exit code -6, cmd '/home/ubuntu/dev_ws/install/turtlebot4_cpp_examples/lib/turtlebot4_cpp_examples/mobilenet_spatial_node --ros-args --params-file /tmp/launch_params_vk06f2mz --params-file /tmp/launch_params_79zw_euo --params-file /tmp/launch_params_n42r00ru --params-file /tmp/launch_params_qay5tqmp'].
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[joy_linux_node-2] [INFO] [1650552893.609735443] [rclcpp]: signal_handler(signal_value=2)
[robot_state_publisher-5] [INFO] [1650552893.609735332] [rclcpp]: signal_handler(signal_value=2)
[teleop_node-3] [INFO] [1650552893.610032255] [rclcpp]: signal_handler(signal_value=2)
[joy_linux_node-2] [INFO] [1650552893.611432890] [joy_linux_node]: joy_node shut down.
[turtlebot4_node-1] [INFO] [1650552893.642632103] [rclcpp]: signal_handler(signal_value=2)
[INFO] [teleop_node-3]: process has finished cleanly [pid 1881]
[INFO] [joy_linux_node-2]: process has finished cleanly [pid 1879]
[INFO] [robot_state_publisher-5]: process has finished cleanly [pid 1886]
[INFO] [turtlebot4_node-1]: process has finished cleanly [pid 1877]

**Comment by Sundareswar23** [comment]
@Kohl-Stefan  you can move followbot.py  previous folder  "turtlebot4_python_examples/", compilation works fine. need to change filename inside setup.py
run the turtlebot4-stop command to use OAK-D camera

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
