### ISSUE TITLE
can not find the Befehl

### ISSUE THREAD

**Issue by HiWiQiao** [turtlebot/turtlebot4_examples#3]
- OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - Built from source or installed:
 - Package version: (if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE`, if from source, give commit hash)
![error](https://github.com/turtlebot/turtlebot4_examples/assets/131516469/9d0735bc-8c3b-4718-aa4c-111f54d93b73)
[](url)

Is this command running on PC or on top of Rasp and why is it reporting errors.

**Comment by hilary-luo** [comment]
@HiWiQiao Apologies that you did not get a response here, is this still something you are looking for assistance for? if so then you need to fill in all of the information about your system and a detailed description of the problem you are facing.
